# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(737, 515)
        Form.setAutoFillBackground(True)
        self.gridLayout_7 = QtWidgets.QGridLayout(Form)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tabConnections = QtWidgets.QWidget()
        self.tabConnections.setObjectName("tabConnections")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tabConnections)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBoxCameraConnection = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBoxCameraConnection.setObjectName("groupBoxCameraConnection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxCameraConnection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelCameraConnectionStatus = QtWidgets.QLabel(self.groupBoxCameraConnection)
        self.labelCameraConnectionStatus.setObjectName("labelCameraConnectionStatus")
        self.gridLayout_2.addWidget(self.labelCameraConnectionStatus, 0, 0, 1, 2)
        self.comboBoxConnectedCameras = QtWidgets.QComboBox(self.groupBoxCameraConnection)
        self.comboBoxConnectedCameras.setObjectName("comboBoxConnectedCameras")
        self.gridLayout_2.addWidget(self.comboBoxConnectedCameras, 1, 0, 1, 2)
        self.buttonScanForCameras = QtWidgets.QPushButton(self.groupBoxCameraConnection)
        self.buttonScanForCameras.setObjectName("buttonScanForCameras")
        self.gridLayout_2.addWidget(self.buttonScanForCameras, 2, 0, 1, 1)
        self.buttonCameraConnectDisconnect = QtWidgets.QPushButton(self.groupBoxCameraConnection)
        self.buttonCameraConnectDisconnect.setObjectName("buttonCameraConnectDisconnect")
        self.gridLayout_2.addWidget(self.buttonCameraConnectDisconnect, 2, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxCameraConnection, 0, 0, 1, 1)
        self.serialControlsGroup = QtWidgets.QGroupBox(self.tabConnections)
        self.serialControlsGroup.setObjectName("serialControlsGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.serialControlsGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.buttonSerialConnect = QtWidgets.QPushButton(self.serialControlsGroup)
        self.buttonSerialConnect.setObjectName("buttonSerialConnect")
        self.gridLayout_5.addWidget(self.buttonSerialConnect, 2, 1, 1, 2)
        self.labelSerialConnected = QtWidgets.QLabel(self.serialControlsGroup)
        self.labelSerialConnected.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelSerialConnected.setObjectName("labelSerialConnected")
        self.gridLayout_5.addWidget(self.labelSerialConnected, 0, 0, 1, 3)
        self.lineeditWriteToSerial = QtWidgets.QLineEdit(self.serialControlsGroup)
        self.lineeditWriteToSerial.setObjectName("lineeditWriteToSerial")
        self.gridLayout_5.addWidget(self.lineeditWriteToSerial, 3, 0, 1, 2)
        self.buttonSerialScan = QtWidgets.QPushButton(self.serialControlsGroup)
        self.buttonSerialScan.setObjectName("buttonSerialScan")
        self.gridLayout_5.addWidget(self.buttonSerialScan, 2, 0, 1, 1)
        self.buttonWriteToSerial = QtWidgets.QPushButton(self.serialControlsGroup)
        self.buttonWriteToSerial.setObjectName("buttonWriteToSerial")
        self.gridLayout_5.addWidget(self.buttonWriteToSerial, 3, 2, 1, 1)
        self.comboboxSerialAvailable = QtWidgets.QComboBox(self.serialControlsGroup)
        self.comboboxSerialAvailable.setObjectName("comboboxSerialAvailable")
        self.gridLayout_5.addWidget(self.comboboxSerialAvailable, 1, 0, 1, 3)
        self.checkBoxReadSerialLive = QtWidgets.QCheckBox(self.serialControlsGroup)
        self.checkBoxReadSerialLive.setEnabled(False)
        self.checkBoxReadSerialLive.setObjectName("checkBoxReadSerialLive")
        self.gridLayout_5.addWidget(self.checkBoxReadSerialLive, 4, 0, 1, 3)
        self.gridLayout_10.addWidget(self.serialControlsGroup, 0, 1, 2, 1)
        self.groupBoxCameraControls = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBoxCameraControls.setEnabled(False)
        self.groupBoxCameraControls.setObjectName("groupBoxCameraControls")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBoxCameraControls)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBoxFramerate = QtWidgets.QSpinBox(self.groupBoxCameraControls)
        self.spinBoxFramerate.setAutoFillBackground(True)
        self.spinBoxFramerate.setKeyboardTracking(False)
        self.spinBoxFramerate.setMinimum(1)
        self.spinBoxFramerate.setMaximum(200)
        self.spinBoxFramerate.setProperty("value", 30)
        self.spinBoxFramerate.setObjectName("spinBoxFramerate")
        self.gridLayout_9.addWidget(self.spinBoxFramerate, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 3, 1, 1)
        self.comboboxCameraExposure = QtWidgets.QComboBox(self.groupBoxCameraControls)
        self.comboboxCameraExposure.setObjectName("comboboxCameraExposure")
        self.gridLayout_9.addWidget(self.comboboxCameraExposure, 0, 4, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 1, 0, 1, 1)
        self.sliderCameraBrightness = QtWidgets.QSlider(self.groupBoxCameraControls)
        self.sliderCameraBrightness.setMinimum(-10)
        self.sliderCameraBrightness.setMaximum(30)
        self.sliderCameraBrightness.setProperty("value", 0)
        self.sliderCameraBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCameraBrightness.setObjectName("sliderCameraBrightness")
        self.gridLayout_9.addWidget(self.sliderCameraBrightness, 1, 1, 1, 5)
        self.labelCameraBrighness = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.labelCameraBrighness.setObjectName("labelCameraBrighness")
        self.gridLayout_9.addWidget(self.labelCameraBrighness, 1, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 2, 0, 1, 1)
        self.sliderCameraGamma = QtWidgets.QSlider(self.groupBoxCameraControls)
        self.sliderCameraGamma.setMaximum(500)
        self.sliderCameraGamma.setPageStep(10)
        self.sliderCameraGamma.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCameraGamma.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderCameraGamma.setObjectName("sliderCameraGamma")
        self.gridLayout_9.addWidget(self.sliderCameraGamma, 2, 1, 1, 5)
        self.labelCameraGamma = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.labelCameraGamma.setObjectName("labelCameraGamma")
        self.gridLayout_9.addWidget(self.labelCameraGamma, 2, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 3, 0, 1, 1)
        self.sliderIRLight = QtWidgets.QSlider(self.groupBoxCameraControls)
        self.sliderIRLight.setEnabled(False)
        self.sliderIRLight.setMaximum(255)
        self.sliderIRLight.setOrientation(QtCore.Qt.Horizontal)
        self.sliderIRLight.setObjectName("sliderIRLight")
        self.gridLayout_9.addWidget(self.sliderIRLight, 3, 1, 1, 5)
        self.label_22 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 3, 6, 1, 1)
        self.buttonCameraPreview = QtWidgets.QPushButton(self.groupBoxCameraControls)
        self.buttonCameraPreview.setCheckable(True)
        self.buttonCameraPreview.setObjectName("buttonCameraPreview")
        self.gridLayout_9.addWidget(self.buttonCameraPreview, 4, 0, 1, 5)
        self.buttonCameraResetProperties = QtWidgets.QPushButton(self.groupBoxCameraControls)
        self.buttonCameraResetProperties.setObjectName("buttonCameraResetProperties")
        self.gridLayout_9.addWidget(self.buttonCameraResetProperties, 4, 5, 1, 2)
        self.checkBoxPreviewWhileRecording = QtWidgets.QCheckBox(self.groupBoxCameraControls)
        self.checkBoxPreviewWhileRecording.setObjectName("checkBoxPreviewWhileRecording")
        self.gridLayout_9.addWidget(self.checkBoxPreviewWhileRecording, 5, 0, 1, 4)
        self.gridLayout_10.addWidget(self.groupBoxCameraControls, 1, 0, 2, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.labelSerialLiveIncoming = QtWidgets.QLabel(self.groupBox_4)
        self.labelSerialLiveIncoming.setObjectName("labelSerialLiveIncoming")
        self.gridLayout_4.addWidget(self.labelSerialLiveIncoming, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.labelSerialLiveTemperature = QtWidgets.QLabel(self.groupBox_4)
        self.labelSerialLiveTemperature.setObjectName("labelSerialLiveTemperature")
        self.gridLayout_4.addWidget(self.labelSerialLiveTemperature, 1, 1, 1, 1)
        self.graphicsViewSerial = PlotWidget(self.groupBox_4)
        self.graphicsViewSerial.setObjectName("graphicsViewSerial")
        self.gridLayout_4.addWidget(self.graphicsViewSerial, 2, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_4, 2, 1, 2, 1)
        self.groupBoxVideoControls = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBoxVideoControls.setEnabled(False)
        self.groupBoxVideoControls.setObjectName("groupBoxVideoControls")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxVideoControls)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelVideoName = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.labelVideoName.setObjectName("labelVideoName")
        self.gridLayout_3.addWidget(self.labelVideoName, 0, 0, 1, 1)
        self.lineeditVideoName = QtWidgets.QLineEdit(self.groupBoxVideoControls)
        self.lineeditVideoName.setEnabled(False)
        self.lineeditVideoName.setObjectName("lineeditVideoName")
        self.gridLayout_3.addWidget(self.lineeditVideoName, 0, 1, 1, 4)
        self.checkboxAutoNaming = QtWidgets.QCheckBox(self.groupBoxVideoControls)
        self.checkboxAutoNaming.setChecked(True)
        self.checkboxAutoNaming.setObjectName("checkboxAutoNaming")
        self.gridLayout_3.addWidget(self.checkboxAutoNaming, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBoxVideoTimeMinutes = QtWidgets.QSpinBox(self.groupBoxVideoControls)
        self.spinBoxVideoTimeMinutes.setProperty("value", 5)
        self.spinBoxVideoTimeMinutes.setObjectName("spinBoxVideoTimeMinutes")
        self.gridLayout_3.addWidget(self.spinBoxVideoTimeMinutes, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.spinBoxVideoTimeSeconds = QtWidgets.QSpinBox(self.groupBoxVideoControls)
        self.spinBoxVideoTimeSeconds.setObjectName("spinBoxVideoTimeSeconds")
        self.gridLayout_3.addWidget(self.spinBoxVideoTimeSeconds, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 5, 1, 1)
        self.buttonSetPath = QtWidgets.QPushButton(self.groupBoxVideoControls)
        self.buttonSetPath.setObjectName("buttonSetPath")
        self.gridLayout_3.addWidget(self.buttonSetPath, 2, 0, 1, 2)
        self.buttonRecordVideo = QtWidgets.QPushButton(self.groupBoxVideoControls)
        self.buttonRecordVideo.setCheckable(True)
        self.buttonRecordVideo.setObjectName("buttonRecordVideo")
        self.gridLayout_3.addWidget(self.buttonRecordVideo, 2, 2, 1, 3)
        self.gridLayout_10.addWidget(self.groupBoxVideoControls, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tabConnections, "")
        self.tabExperiment = QtWidgets.QWidget()
        self.tabExperiment.setObjectName("tabExperiment")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tabExperiment)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lightStimuliGroup = QtWidgets.QGroupBox(self.tabExperiment)
        self.lightStimuliGroup.setEnabled(True)
        self.lightStimuliGroup.setObjectName("lightStimuliGroup")
        self.widgetLEDSliders = QtWidgets.QWidget(self.lightStimuliGroup)
        self.widgetLEDSliders.setEnabled(True)
        self.widgetLEDSliders.setGeometry(QtCore.QRect(10, 10, 71, 171))
        self.widgetLEDSliders.setObjectName("widgetLEDSliders")
        self.labelRedSliderValue = QtWidgets.QLabel(self.widgetLEDSliders)
        self.labelRedSliderValue.setGeometry(QtCore.QRect(0, 10, 20, 16))
        self.labelRedSliderValue.setObjectName("labelRedSliderValue")
        self.sliderRed = QtWidgets.QSlider(self.widgetLEDSliders)
        self.sliderRed.setGeometry(QtCore.QRect(0, 29, 19, 141))
        self.sliderRed.setMaximum(255)
        self.sliderRed.setOrientation(QtCore.Qt.Vertical)
        self.sliderRed.setObjectName("sliderRed")
        self.labelBlueSliderValue = QtWidgets.QLabel(self.widgetLEDSliders)
        self.labelBlueSliderValue.setGeometry(QtCore.QRect(48, 10, 19, 16))
        self.labelBlueSliderValue.setObjectName("labelBlueSliderValue")
        self.labelGreenSliderValue = QtWidgets.QLabel(self.widgetLEDSliders)
        self.labelGreenSliderValue.setGeometry(QtCore.QRect(23, 10, 19, 16))
        self.labelGreenSliderValue.setObjectName("labelGreenSliderValue")
        self.sliderBlue = QtWidgets.QSlider(self.widgetLEDSliders)
        self.sliderBlue.setGeometry(QtCore.QRect(50, 29, 19, 141))
        self.sliderBlue.setMaximum(255)
        self.sliderBlue.setOrientation(QtCore.Qt.Vertical)
        self.sliderBlue.setObjectName("sliderBlue")
        self.sliderGreen = QtWidgets.QSlider(self.widgetLEDSliders)
        self.sliderGreen.setGeometry(QtCore.QRect(25, 29, 19, 141))
        self.sliderGreen.setMaximum(255)
        self.sliderGreen.setOrientation(QtCore.Qt.Vertical)
        self.sliderGreen.setObjectName("sliderGreen")
        self.widget_2 = QtWidgets.QWidget(self.lightStimuliGroup)
        self.widget_2.setGeometry(QtCore.QRect(100, 10, 221, 191))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.labelLightStimSettings = QtWidgets.QLabel(self.widget_2)
        self.labelLightStimSettings.setObjectName("labelLightStimSettings")
        self.gridLayout_8.addWidget(self.labelLightStimSettings, 0, 0, 1, 3)
        self.labelLightStimTypeLED = QtWidgets.QLabel(self.widget_2)
        self.labelLightStimTypeLED.setObjectName("labelLightStimTypeLED")
        self.gridLayout_8.addWidget(self.labelLightStimTypeLED, 1, 0, 1, 1)
        self.toggleWhiteColor = QtWidgets.QSlider(self.widget_2)
        self.toggleWhiteColor.setMaximum(1)
        self.toggleWhiteColor.setOrientation(QtCore.Qt.Horizontal)
        self.toggleWhiteColor.setObjectName("toggleWhiteColor")
        self.gridLayout_8.addWidget(self.toggleWhiteColor, 1, 1, 1, 2)
        self.labelLightStimTypeWhite = QtWidgets.QLabel(self.widget_2)
        self.labelLightStimTypeWhite.setObjectName("labelLightStimTypeWhite")
        self.gridLayout_8.addWidget(self.labelLightStimTypeWhite, 1, 3, 1, 1)
        self.labelStimName = QtWidgets.QLabel(self.widget_2)
        self.labelStimName.setObjectName("labelStimName")
        self.gridLayout_8.addWidget(self.labelStimName, 2, 0, 1, 1)
        self.lineeditLightStimName = QtWidgets.QLineEdit(self.widget_2)
        self.lineeditLightStimName.setObjectName("lineeditLightStimName")
        self.gridLayout_8.addWidget(self.lineeditLightStimName, 2, 2, 1, 3)
        self.labelTestStim = QtWidgets.QLabel(self.widget_2)
        self.labelTestStim.setObjectName("labelTestStim")
        self.gridLayout_8.addWidget(self.labelTestStim, 3, 0, 1, 2)
        self.spinboxStimStart = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.spinboxStimStart.setMaximum(1000.0)
        self.spinboxStimStart.setObjectName("spinboxStimStart")
        self.gridLayout_8.addWidget(self.spinboxStimStart, 3, 2, 1, 2)
        self.labelSeconds1 = QtWidgets.QLabel(self.widget_2)
        self.labelSeconds1.setObjectName("labelSeconds1")
        self.gridLayout_8.addWidget(self.labelSeconds1, 3, 4, 1, 1)
        self.labelStimDuration = QtWidgets.QLabel(self.widget_2)
        self.labelStimDuration.setObjectName("labelStimDuration")
        self.gridLayout_8.addWidget(self.labelStimDuration, 4, 0, 1, 2)
        self.spinboxStimDuration = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.spinboxStimDuration.setMaximum(1000.0)
        self.spinboxStimDuration.setObjectName("spinboxStimDuration")
        self.gridLayout_8.addWidget(self.spinboxStimDuration, 4, 2, 1, 2)
        self.labelSeconds2 = QtWidgets.QLabel(self.widget_2)
        self.labelSeconds2.setObjectName("labelSeconds2")
        self.gridLayout_8.addWidget(self.labelSeconds2, 4, 4, 1, 1)
        self.buttonSaveStim = QtWidgets.QPushButton(self.widget_2)
        self.buttonSaveStim.setObjectName("buttonSaveStim")
        self.gridLayout_8.addWidget(self.buttonSaveStim, 5, 2, 1, 2)
        self.gridLayout_12.addWidget(self.lightStimuliGroup, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.graphicsView = PlotWidget(self.groupBox_2)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_15.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonDeleteSelectedStim = QtWidgets.QPushButton(self.widget)
        self.buttonDeleteSelectedStim.setObjectName("buttonDeleteSelectedStim")
        self.gridLayout.addWidget(self.buttonDeleteSelectedStim, 1, 0, 1, 1)
        self.buttonSaveStimulusProfile = QtWidgets.QPushButton(self.widget)
        self.buttonSaveStimulusProfile.setObjectName("buttonSaveStimulusProfile")
        self.gridLayout.addWidget(self.buttonSaveStimulusProfile, 1, 1, 1, 1)
        self.buttonDeleteAllStims = QtWidgets.QPushButton(self.widget)
        self.buttonDeleteAllStims.setObjectName("buttonDeleteAllStims")
        self.gridLayout.addWidget(self.buttonDeleteAllStims, 2, 0, 1, 1)
        self.buttonLoadStimulusProfile = QtWidgets.QPushButton(self.widget)
        self.buttonLoadStimulusProfile.setObjectName("buttonLoadStimulusProfile")
        self.gridLayout.addWidget(self.buttonLoadStimulusProfile, 2, 1, 1, 1)
        self.comboBoxSelectStimId = QtWidgets.QComboBox(self.widget)
        self.comboBoxSelectStimId.setObjectName("comboBoxSelectStimId")
        self.gridLayout.addWidget(self.comboBoxSelectStimId, 0, 0, 1, 2)
        self.gridLayout_15.addWidget(self.widget, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_2, 0, 2, 1, 2)
        self.groupBoxVibrationStimuli = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupBoxVibrationStimuli.setEnabled(True)
        self.groupBoxVibrationStimuli.setObjectName("groupBoxVibrationStimuli")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxVibrationStimuli)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinBoxVibrationFrequency = QtWidgets.QSpinBox(self.groupBoxVibrationStimuli)
        self.spinBoxVibrationFrequency.setMinimum(31)
        self.spinBoxVibrationFrequency.setMaximum(999)
        self.spinBoxVibrationFrequency.setObjectName("spinBoxVibrationFrequency")
        self.gridLayout_11.addWidget(self.spinBoxVibrationFrequency, 4, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label_13.setObjectName("label_13")
        self.gridLayout_11.addWidget(self.label_13, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 3, 0, 1, 2)
        self.spinBoxVibrationDuration = QtWidgets.QDoubleSpinBox(self.groupBoxVibrationStimuli)
        self.spinBoxVibrationDuration.setObjectName("spinBoxVibrationDuration")
        self.gridLayout_11.addWidget(self.spinBoxVibrationDuration, 11, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label_17.setObjectName("label_17")
        self.gridLayout_11.addWidget(self.label_17, 10, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 11, 2, 1, 2)
        self.buttonSaveVibrationStim = QtWidgets.QPushButton(self.groupBoxVibrationStimuli)
        self.buttonSaveVibrationStim.setObjectName("buttonSaveVibrationStim")
        self.gridLayout_11.addWidget(self.buttonSaveVibrationStim, 12, 1, 1, 3)
        self.label_23 = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 1, 0, 1, 2)
        self.lineeditVibrationStimName = QtWidgets.QLineEdit(self.groupBoxVibrationStimuli)
        self.lineeditVibrationStimName.setObjectName("lineeditVibrationStimName")
        self.gridLayout_11.addWidget(self.lineeditVibrationStimName, 2, 0, 1, 4)
        self.label_25 = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 8, 0, 1, 2)
        self.spinBoxVibrationStart = QtWidgets.QDoubleSpinBox(self.groupBoxVibrationStimuli)
        self.spinBoxVibrationStart.setObjectName("spinBoxVibrationStart")
        self.gridLayout_11.addWidget(self.spinBoxVibrationStart, 9, 0, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.groupBoxVibrationStimuli)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 9, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBoxVibrationStimuli, 1, 0, 1, 1)
        self.groupboxMetaData = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupboxMetaData.setObjectName("groupboxMetaData")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupboxMetaData)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.widgetMetaData = QtWidgets.QWidget(self.groupboxMetaData)
        self.widgetMetaData.setObjectName("widgetMetaData")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widgetMetaData)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.lineeditExperimentName = QtWidgets.QLineEdit(self.widgetMetaData)
        self.lineeditExperimentName.setEnabled(False)
        self.lineeditExperimentName.setObjectName("lineeditExperimentName")
        self.horizontalLayout_4.addWidget(self.lineeditExperimentName)
        self.checkBoxExperimentAutonaming = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkBoxExperimentAutonaming.setChecked(True)
        self.checkBoxExperimentAutonaming.setObjectName("checkBoxExperimentAutonaming")
        self.horizontalLayout_4.addWidget(self.checkBoxExperimentAutonaming)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 0, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.spinBoxExperimentDurationMinutes = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinBoxExperimentDurationMinutes.setProperty("value", 5)
        self.spinBoxExperimentDurationMinutes.setObjectName("spinBoxExperimentDurationMinutes")
        self.horizontalLayout.addWidget(self.spinBoxExperimentDurationMinutes)
        self.label_14 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.spinBoxExperimentDurationSeconds = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinBoxExperimentDurationSeconds.setObjectName("spinBoxExperimentDurationSeconds")
        self.horizontalLayout.addWidget(self.spinBoxExperimentDurationSeconds)
        self.label_16 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.gridLayout_6.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.spinboxCrowdsize = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinboxCrowdsize.setProperty("value", 1)
        self.spinboxCrowdsize.setObjectName("spinboxCrowdsize")
        self.horizontalLayout_2.addWidget(self.spinboxCrowdsize)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_26 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.dateTimeEditHatching = QtWidgets.QDateTimeEdit(self.widgetMetaData)
        self.dateTimeEditHatching.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.dateTimeEditHatching.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.dateTimeEditHatching.setCalendarPopup(True)
        self.dateTimeEditHatching.setObjectName("dateTimeEditHatching")
        self.horizontalLayout_3.addWidget(self.dateTimeEditHatching)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.checkboxMetaDataDechorionation = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkboxMetaDataDechorionation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxMetaDataDechorionation.setObjectName("checkboxMetaDataDechorionation")
        self.gridLayout_6.addWidget(self.checkboxMetaDataDechorionation, 2, 2, 1, 1)
        self.checkboxMetaDataGenetics = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkboxMetaDataGenetics.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxMetaDataGenetics.setObjectName("checkboxMetaDataGenetics")
        self.gridLayout_6.addWidget(self.checkboxMetaDataGenetics, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelMetaDataGenetics = QtWidgets.QLabel(self.widgetMetaData)
        self.labelMetaDataGenetics.setObjectName("labelMetaDataGenetics")
        self.horizontalLayout_5.addWidget(self.labelMetaDataGenetics)
        self.lineeditMetaDataGenetics = QtWidgets.QLineEdit(self.widgetMetaData)
        self.lineeditMetaDataGenetics.setObjectName("lineeditMetaDataGenetics")
        self.horizontalLayout_5.addWidget(self.lineeditMetaDataGenetics)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 3, 1, 1, 2)
        self.checkboxMetaDataDrugs = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkboxMetaDataDrugs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxMetaDataDrugs.setObjectName("checkboxMetaDataDrugs")
        self.gridLayout_6.addWidget(self.checkboxMetaDataDrugs, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMetaDataDrugName = QtWidgets.QLabel(self.widgetMetaData)
        self.labelMetaDataDrugName.setObjectName("labelMetaDataDrugName")
        self.horizontalLayout_6.addWidget(self.labelMetaDataDrugName)
        self.lineeditMetaDataDrugName = QtWidgets.QLineEdit(self.widgetMetaData)
        self.lineeditMetaDataDrugName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineeditMetaDataDrugName.setObjectName("lineeditMetaDataDrugName")
        self.horizontalLayout_6.addWidget(self.lineeditMetaDataDrugName)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 4, 1, 1, 2)
        self.gridLayout_13.addWidget(self.widgetMetaData, 0, 0, 1, 2)
        self.buttonSetWorkingDirectory = QtWidgets.QPushButton(self.groupboxMetaData)
        self.buttonSetWorkingDirectory.setObjectName("buttonSetWorkingDirectory")
        self.gridLayout_13.addWidget(self.buttonSetWorkingDirectory, 1, 0, 1, 1)
        self.buttonStartExperiment = QtWidgets.QPushButton(self.groupboxMetaData)
        self.buttonStartExperiment.setCheckable(True)
        self.buttonStartExperiment.setObjectName("buttonStartExperiment")
        self.gridLayout_13.addWidget(self.buttonStartExperiment, 1, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupboxMetaData, 1, 1, 1, 2)
        self.groupBoxLazyMode = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupBoxLazyMode.setObjectName("groupBoxLazyMode")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBoxLazyMode)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelLazyMode = QtWidgets.QLabel(self.groupBoxLazyMode)
        self.labelLazyMode.setObjectName("labelLazyMode")
        self.horizontalLayout_7.addWidget(self.labelLazyMode)
        self.spinBoxLazyMode = QtWidgets.QSpinBox(self.groupBoxLazyMode)
        self.spinBoxLazyMode.setObjectName("spinBoxLazyMode")
        self.horizontalLayout_7.addWidget(self.spinBoxLazyMode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.buttonLazyMode = QtWidgets.QPushButton(self.groupBoxLazyMode)
        self.buttonLazyMode.setObjectName("buttonLazyMode")
        self.verticalLayout_3.addWidget(self.buttonLazyMode)
        self.gridLayout_14.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBoxLazyMode, 1, 3, 1, 1)
        self.tabWidget.addTab(self.tabExperiment, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.sliderBlue.sliderMoved['int'].connect(self.labelBlueSliderValue.setNum)
        self.sliderGreen.sliderMoved['int'].connect(self.labelGreenSliderValue.setNum)
        self.sliderRed.sliderMoved['int'].connect(self.labelRedSliderValue.setNum)
        self.sliderCameraBrightness.valueChanged['int'].connect(self.labelCameraBrighness.setNum)
        self.sliderIRLight.valueChanged['int'].connect(self.label_22.setNum)
        self.checkboxMetaDataGenetics.toggled['bool'].connect(self.labelMetaDataGenetics.setVisible)
        self.checkboxMetaDataGenetics.toggled['bool'].connect(self.lineeditMetaDataGenetics.setVisible)
        self.checkboxMetaDataDrugs.toggled['bool'].connect(self.labelMetaDataDrugName.setVisible)
        self.checkboxMetaDataDrugs.toggled['bool'].connect(self.lineeditMetaDataDrugName.setVisible)
        self.checkBoxExperimentAutonaming.toggled['bool'].connect(self.lineeditExperimentName.setDisabled)
        self.checkboxAutoNaming.toggled['bool'].connect(self.lineeditVideoName.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxCameraConnection.setTitle(_translate("Form", "Connect To Camera"))
        self.labelCameraConnectionStatus.setText(_translate("Form", "Status: Not Connected"))
        self.buttonScanForCameras.setText(_translate("Form", "scan"))
        self.buttonCameraConnectDisconnect.setText(_translate("Form", "connect"))
        self.serialControlsGroup.setTitle(_translate("Form", "Serial Connection to Setup"))
        self.buttonSerialConnect.setText(_translate("Form", "Connect"))
        self.labelSerialConnected.setText(_translate("Form", "Status: Not Connected"))
        self.lineeditWriteToSerial.setToolTip(_translate("Form", "<html><head/><body><p>Write to the Controller:<br/>White light on: &quot;wS&quot;<br/>White light off: &quot;wC&quot;</p><p>For LEDs: &quot;n&quot;+ nine digits setting RGB values<br/>example: &quot;n000255000&quot; set green leds on.<br/>LEDs off: &quot;nC&quot;</p><p>set IR light: &quot;i&quot;+three digits<br/>example: &quot;i255&quot; sets IR to full power.</p></body></html>"))
        self.buttonSerialScan.setText(_translate("Form", "Scan"))
        self.buttonWriteToSerial.setText(_translate("Form", "Send"))
        self.checkBoxReadSerialLive.setText(_translate("Form", "Read Serial Live"))
        self.groupBoxCameraControls.setTitle(_translate("Form", "Camera Controls"))
        self.label_5.setText(_translate("Form", "Framerate"))
        self.label_6.setText(_translate("Form", "fps"))
        self.label_9.setText(_translate("Form", "Exposure"))
        self.label_7.setText(_translate("Form", "Brightness"))
        self.labelCameraBrighness.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Gamma"))
        self.sliderCameraGamma.setToolTip(_translate("Form", "<html><head/><body><p>Gamma calculations will not be performed for framerates higher than 50fps.</p><p><br/></p></body></html>"))
        self.labelCameraGamma.setText(_translate("Form", "0"))
        self.label_21.setText(_translate("Form", "IR Light"))
        self.label_22.setText(_translate("Form", "0"))
        self.buttonCameraPreview.setText(_translate("Form", "Live Preview"))
        self.buttonCameraResetProperties.setText(_translate("Form", "reset"))
        self.checkBoxPreviewWhileRecording.setToolTip(_translate("Form", "<html><head/><body><p>Check this box to show the camerafeed during recordings. Recommended to uncheck when multiple recordings are being acquired.</p><p><br/></p></body></html>"))
        self.checkBoxPreviewWhileRecording.setText(_translate("Form", "Preview While Recording"))
        self.groupBox_4.setTitle(_translate("Form", "Live Data From Serial Connection"))
        self.label_19.setText(_translate("Form", "Time (seconds):"))
        self.labelSerialLiveIncoming.setText(_translate("Form", "[No Data Yet]"))
        self.label_20.setText(_translate("Form", "Temperature:"))
        self.labelSerialLiveTemperature.setText(_translate("Form", "[No Data Yet]"))
        self.groupBoxVideoControls.setTitle(_translate("Form", "VideoControls"))
        self.labelVideoName.setText(_translate("Form", "Video Name"))
        self.checkboxAutoNaming.setText(_translate("Form", "Automatic"))
        self.label_2.setText(_translate("Form", "Duration"))
        self.label_3.setText(_translate("Form", "minutes"))
        self.label_4.setText(_translate("Form", "seconds"))
        self.buttonSetPath.setText(_translate("Form", "Set Path"))
        self.buttonRecordVideo.setText(_translate("Form", "Record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConnections), _translate("Form", "Camera and Serial Connection"))
        self.lightStimuliGroup.setTitle(_translate("Form", "LightStimuli"))
        self.labelRedSliderValue.setText(_translate("Form", "0"))
        self.labelBlueSliderValue.setText(_translate("Form", "0"))
        self.labelGreenSliderValue.setText(_translate("Form", "0"))
        self.labelLightStimSettings.setText(_translate("Form", "Lightstimulus type:"))
        self.labelLightStimTypeLED.setText(_translate("Form", "LED Stim"))
        self.labelLightStimTypeWhite.setText(_translate("Form", "White Light"))
        self.labelStimName.setText(_translate("Form", "Stim Name:"))
        self.lineeditLightStimName.setToolTip(_translate("Form", "Give your stimulus a wonderful name!"))
        self.lineeditLightStimName.setText(_translate("Form", "GeneralStimName"))
        self.lineeditLightStimName.setPlaceholderText(_translate("Form", "GeneralLightStim"))
        self.labelTestStim.setText(_translate("Form", "Start stim at:"))
        self.labelSeconds1.setText(_translate("Form", "seconds"))
        self.labelStimDuration.setText(_translate("Form", "Stim Duration:"))
        self.labelSeconds2.setText(_translate("Form", "seconds"))
        self.buttonSaveStim.setText(_translate("Form", "Add to Stims"))
        self.groupBox_2.setTitle(_translate("Form", "ExperimentView"))
        self.buttonDeleteSelectedStim.setText(_translate("Form", "Delete Stim"))
        self.buttonSaveStimulusProfile.setText(_translate("Form", "Save Stimulus Profile"))
        self.buttonDeleteAllStims.setText(_translate("Form", "Delete All Stims"))
        self.buttonLoadStimulusProfile.setText(_translate("Form", "Load Stimulus Profile"))
        self.groupBoxVibrationStimuli.setTitle(_translate("Form", "VibrationStimuli"))
        self.spinBoxVibrationFrequency.setToolTip(_translate("Form", "<html><head/><body><p>Must be between 31 and 999 Hz.</p></body></html>"))
        self.label_13.setText(_translate("Form", "Hz"))
        self.label.setText(_translate("Form", "Frequency:"))
        self.label_17.setText(_translate("Form", "Duration:"))
        self.label_18.setText(_translate("Form", "sec."))
        self.buttonSaveVibrationStim.setText(_translate("Form", "Add to Stims"))
        self.label_23.setText(_translate("Form", "Stim Name:"))
        self.label_25.setText(_translate("Form", "Start at:"))
        self.label_24.setText(_translate("Form", "sec."))
        self.groupboxMetaData.setTitle(_translate("Form", "MetaData"))
        self.label_11.setText(_translate("Form", "Experiment Name:"))
        self.checkBoxExperimentAutonaming.setText(_translate("Form", "Auto"))
        self.label_15.setText(_translate("Form", "Duration"))
        self.label_14.setText(_translate("Form", "minutes"))
        self.label_16.setText(_translate("Form", "seconds"))
        self.label_10.setText(_translate("Form", "Crowdsize"))
        self.label_26.setToolTip(_translate("Form", "<html><head/><body><p>Hours Post Hatching</p></body></html>"))
        self.label_26.setText(_translate("Form", "HatchingTime"))
        self.dateTimeEditHatching.setDisplayFormat(_translate("Form", "dd.MM.yyyy HH:mm"))
        self.checkboxMetaDataDechorionation.setText(_translate("Form", "Dechorionated"))
        self.checkboxMetaDataGenetics.setText(_translate("Form", "Genetics"))
        self.labelMetaDataGenetics.setText(_translate("Form", "Genotype:"))
        self.lineeditMetaDataGenetics.setText(_translate("Form", "None"))
        self.checkboxMetaDataDrugs.setText(_translate("Form", "Drugs"))
        self.labelMetaDataDrugName.setText(_translate("Form", "Drug name:"))
        self.lineeditMetaDataDrugName.setText(_translate("Form", "None"))
        self.buttonSetWorkingDirectory.setText(_translate("Form", "Set Working Directory"))
        self.buttonStartExperiment.setText(_translate("Form", "Start Experiment"))
        self.groupBoxLazyMode.setTitle(_translate("Form", "Lazy Mode"))
        self.labelLazyMode.setText(_translate("Form", "Experiments:"))
        self.buttonLazyMode.setText(_translate("Form", "LazyMode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExperiment), _translate("Form", "Experiment Settings"))

from pyqtgraph import PlotWidget
