# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(806, 600)
        Form.setAutoFillBackground(True)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tabConnections = QtWidgets.QWidget()
        self.tabConnections.setObjectName("tabConnections")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(315, 155, 281, 191))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.labelSerialLiveIncoming = QtWidgets.QLabel(self.groupBox_4)
        self.labelSerialLiveIncoming.setObjectName("labelSerialLiveIncoming")
        self.gridLayout_4.addWidget(self.labelSerialLiveIncoming, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.labelSerialLiveTemperature = QtWidgets.QLabel(self.groupBox_4)
        self.labelSerialLiveTemperature.setObjectName("labelSerialLiveTemperature")
        self.gridLayout_4.addWidget(self.labelSerialLiveTemperature, 1, 1, 1, 1)
        self.graphicsViewSerial = PlotWidget(self.groupBox_4)
        self.graphicsViewSerial.setObjectName("graphicsViewSerial")
        self.gridLayout_4.addWidget(self.graphicsViewSerial, 2, 0, 1, 2)
        self.serialControlsGroup = QtWidgets.QGroupBox(self.tabConnections)
        self.serialControlsGroup.setGeometry(QtCore.QRect(315, 0, 281, 153))
        self.serialControlsGroup.setObjectName("serialControlsGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.serialControlsGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.buttonSerialConnect = QtWidgets.QPushButton(self.serialControlsGroup)
        self.buttonSerialConnect.setObjectName("buttonSerialConnect")
        self.gridLayout_5.addWidget(self.buttonSerialConnect, 2, 1, 1, 2)
        self.labelSerialConnected = QtWidgets.QLabel(self.serialControlsGroup)
        self.labelSerialConnected.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelSerialConnected.setObjectName("labelSerialConnected")
        self.gridLayout_5.addWidget(self.labelSerialConnected, 0, 0, 1, 3)
        self.lineeditWriteToSerial = QtWidgets.QLineEdit(self.serialControlsGroup)
        self.lineeditWriteToSerial.setObjectName("lineeditWriteToSerial")
        self.gridLayout_5.addWidget(self.lineeditWriteToSerial, 3, 0, 1, 2)
        self.buttonSerialScan = QtWidgets.QPushButton(self.serialControlsGroup)
        self.buttonSerialScan.setObjectName("buttonSerialScan")
        self.gridLayout_5.addWidget(self.buttonSerialScan, 2, 0, 1, 1)
        self.buttonWriteToSerial = QtWidgets.QPushButton(self.serialControlsGroup)
        self.buttonWriteToSerial.setObjectName("buttonWriteToSerial")
        self.gridLayout_5.addWidget(self.buttonWriteToSerial, 3, 2, 1, 1)
        self.comboboxSerialAvailable = QtWidgets.QComboBox(self.serialControlsGroup)
        self.comboboxSerialAvailable.setObjectName("comboboxSerialAvailable")
        self.gridLayout_5.addWidget(self.comboboxSerialAvailable, 1, 0, 1, 3)
        self.checkBoxReadSerialLive = QtWidgets.QCheckBox(self.serialControlsGroup)
        self.checkBoxReadSerialLive.setEnabled(False)
        self.checkBoxReadSerialLive.setObjectName("checkBoxReadSerialLive")
        self.gridLayout_5.addWidget(self.checkBoxReadSerialLive, 4, 0, 1, 3)
        self.groupBoxCameraControls = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBoxCameraControls.setEnabled(False)
        self.groupBoxCameraControls.setGeometry(QtCore.QRect(0, 100, 311, 191))
        self.groupBoxCameraControls.setObjectName("groupBoxCameraControls")
        self.buttonCameraPreview = QtWidgets.QPushButton(self.groupBoxCameraControls)
        self.buttonCameraPreview.setGeometry(QtCore.QRect(10, 149, 211, 23))
        self.buttonCameraPreview.setCheckable(True)
        self.buttonCameraPreview.setObjectName("buttonCameraPreview")
        self.label_5 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_5.setGeometry(QtCore.QRect(10, 28, 50, 16))
        self.label_5.setObjectName("label_5")
        self.spinBoxFramerate = QtWidgets.QSpinBox(self.groupBoxCameraControls)
        self.spinBoxFramerate.setGeometry(QtCore.QRect(66, 28, 43, 20))
        self.spinBoxFramerate.setAutoFillBackground(True)
        self.spinBoxFramerate.setKeyboardTracking(False)
        self.spinBoxFramerate.setMinimum(1)
        self.spinBoxFramerate.setMaximum(200)
        self.spinBoxFramerate.setProperty("value", 30)
        self.spinBoxFramerate.setObjectName("spinBoxFramerate")
        self.label_6 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_6.setGeometry(QtCore.QRect(115, 28, 16, 16))
        self.label_6.setObjectName("label_6")
        self.comboboxCameraExposure = QtWidgets.QComboBox(self.groupBoxCameraControls)
        self.comboboxCameraExposure.setGeometry(QtCore.QRect(232, 28, 69, 20))
        self.comboboxCameraExposure.setObjectName("comboboxCameraExposure")
        self.label_9 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_9.setGeometry(QtCore.QRect(156, 28, 45, 16))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_7.setGeometry(QtCore.QRect(10, 59, 50, 16))
        self.label_7.setObjectName("label_7")
        self.sliderCameraBrightness = QtWidgets.QSlider(self.groupBoxCameraControls)
        self.sliderCameraBrightness.setGeometry(QtCore.QRect(70, 60, 201, 19))
        self.sliderCameraBrightness.setMinimum(-10)
        self.sliderCameraBrightness.setMaximum(30)
        self.sliderCameraBrightness.setProperty("value", 0)
        self.sliderCameraBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCameraBrightness.setObjectName("sliderCameraBrightness")
        self.labelCameraBrighness = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.labelCameraBrighness.setGeometry(QtCore.QRect(281, 59, 16, 16))
        self.labelCameraBrighness.setObjectName("labelCameraBrighness")
        self.label_8 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_8.setGeometry(QtCore.QRect(10, 89, 35, 16))
        self.label_8.setObjectName("label_8")
        self.sliderCameraGamma = QtWidgets.QSlider(self.groupBoxCameraControls)
        self.sliderCameraGamma.setGeometry(QtCore.QRect(66, 89, 201, 19))
        self.sliderCameraGamma.setMaximum(30)
        self.sliderCameraGamma.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCameraGamma.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderCameraGamma.setObjectName("sliderCameraGamma")
        self.labelCameraGamma = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.labelCameraGamma.setGeometry(QtCore.QRect(280, 89, 16, 16))
        self.labelCameraGamma.setObjectName("labelCameraGamma")
        self.label_21 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_21.setGeometry(QtCore.QRect(10, 119, 37, 16))
        self.label_21.setObjectName("label_21")
        self.sliderIRLight = QtWidgets.QSlider(self.groupBoxCameraControls)
        self.sliderIRLight.setEnabled(False)
        self.sliderIRLight.setGeometry(QtCore.QRect(66, 119, 201, 19))
        self.sliderIRLight.setMaximum(255)
        self.sliderIRLight.setOrientation(QtCore.Qt.Horizontal)
        self.sliderIRLight.setObjectName("sliderIRLight")
        self.label_22 = QtWidgets.QLabel(self.groupBoxCameraControls)
        self.label_22.setGeometry(QtCore.QRect(280, 119, 16, 16))
        self.label_22.setObjectName("label_22")
        self.buttonCameraResetProperties = QtWidgets.QPushButton(self.groupBoxCameraControls)
        self.buttonCameraResetProperties.setGeometry(QtCore.QRect(220, 150, 75, 23))
        self.buttonCameraResetProperties.setObjectName("buttonCameraResetProperties")
        self.groupBoxVideoControls = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBoxVideoControls.setEnabled(False)
        self.groupBoxVideoControls.setGeometry(QtCore.QRect(0, 290, 311, 108))
        self.groupBoxVideoControls.setObjectName("groupBoxVideoControls")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxVideoControls)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelVideoName = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.labelVideoName.setObjectName("labelVideoName")
        self.gridLayout_3.addWidget(self.labelVideoName, 0, 0, 1, 1)
        self.lineeditVideoName = QtWidgets.QLineEdit(self.groupBoxVideoControls)
        self.lineeditVideoName.setEnabled(False)
        self.lineeditVideoName.setObjectName("lineeditVideoName")
        self.gridLayout_3.addWidget(self.lineeditVideoName, 0, 1, 1, 4)
        self.checkboxAutoNaming = QtWidgets.QCheckBox(self.groupBoxVideoControls)
        self.checkboxAutoNaming.setChecked(True)
        self.checkboxAutoNaming.setObjectName("checkboxAutoNaming")
        self.gridLayout_3.addWidget(self.checkboxAutoNaming, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBoxVideoTimeMinutes = QtWidgets.QSpinBox(self.groupBoxVideoControls)
        self.spinBoxVideoTimeMinutes.setProperty("value", 5)
        self.spinBoxVideoTimeMinutes.setObjectName("spinBoxVideoTimeMinutes")
        self.gridLayout_3.addWidget(self.spinBoxVideoTimeMinutes, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 1)
        self.spinBoxVideoTimeSeconds = QtWidgets.QSpinBox(self.groupBoxVideoControls)
        self.spinBoxVideoTimeSeconds.setObjectName("spinBoxVideoTimeSeconds")
        self.gridLayout_3.addWidget(self.spinBoxVideoTimeSeconds, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxVideoControls)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 5, 1, 1)
        self.buttonSetPath = QtWidgets.QPushButton(self.groupBoxVideoControls)
        self.buttonSetPath.setObjectName("buttonSetPath")
        self.gridLayout_3.addWidget(self.buttonSetPath, 2, 0, 1, 2)
        self.buttonRecordVideo = QtWidgets.QPushButton(self.groupBoxVideoControls)
        self.buttonRecordVideo.setCheckable(True)
        self.buttonRecordVideo.setObjectName("buttonRecordVideo")
        self.gridLayout_3.addWidget(self.buttonRecordVideo, 2, 2, 1, 3)
        self.groupBoxCameraConnection = QtWidgets.QGroupBox(self.tabConnections)
        self.groupBoxCameraConnection.setGeometry(QtCore.QRect(0, 0, 311, 101))
        self.groupBoxCameraConnection.setObjectName("groupBoxCameraConnection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxCameraConnection)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelCameraConnectionStatus = QtWidgets.QLabel(self.groupBoxCameraConnection)
        self.labelCameraConnectionStatus.setObjectName("labelCameraConnectionStatus")
        self.gridLayout_2.addWidget(self.labelCameraConnectionStatus, 0, 0, 1, 2)
        self.comboBoxConnectedCameras = QtWidgets.QComboBox(self.groupBoxCameraConnection)
        self.comboBoxConnectedCameras.setObjectName("comboBoxConnectedCameras")
        self.gridLayout_2.addWidget(self.comboBoxConnectedCameras, 1, 0, 1, 2)
        self.buttonScanForCameras = QtWidgets.QPushButton(self.groupBoxCameraConnection)
        self.buttonScanForCameras.setObjectName("buttonScanForCameras")
        self.gridLayout_2.addWidget(self.buttonScanForCameras, 2, 0, 1, 1)
        self.buttonCameraConnectDisconnect = QtWidgets.QPushButton(self.groupBoxCameraConnection)
        self.buttonCameraConnectDisconnect.setObjectName("buttonCameraConnectDisconnect")
        self.gridLayout_2.addWidget(self.buttonCameraConnectDisconnect, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tabConnections, "")
        self.tabExperiment = QtWidgets.QWidget()
        self.tabExperiment.setObjectName("tabExperiment")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 0, 341, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView = PlotWidget(self.groupBox_2)
        self.graphicsView.setGeometry(QtCore.QRect(5, 20, 331, 51))
        self.graphicsView.setObjectName("graphicsView")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 73, 321, 96))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonDeleteSelectedStim = QtWidgets.QPushButton(self.widget)
        self.buttonDeleteSelectedStim.setObjectName("buttonDeleteSelectedStim")
        self.gridLayout.addWidget(self.buttonDeleteSelectedStim, 1, 0, 1, 1)
        self.buttonSaveStimulusProfile = QtWidgets.QPushButton(self.widget)
        self.buttonSaveStimulusProfile.setObjectName("buttonSaveStimulusProfile")
        self.gridLayout.addWidget(self.buttonSaveStimulusProfile, 1, 1, 1, 1)
        self.buttonDeleteAllStims = QtWidgets.QPushButton(self.widget)
        self.buttonDeleteAllStims.setObjectName("buttonDeleteAllStims")
        self.gridLayout.addWidget(self.buttonDeleteAllStims, 2, 0, 1, 1)
        self.buttonLoadStimulusProfile = QtWidgets.QPushButton(self.widget)
        self.buttonLoadStimulusProfile.setObjectName("buttonLoadStimulusProfile")
        self.gridLayout.addWidget(self.buttonLoadStimulusProfile, 2, 1, 1, 1)
        self.comboBoxSelectStimId = QtWidgets.QComboBox(self.widget)
        self.comboBoxSelectStimId.setObjectName("comboBoxSelectStimId")
        self.gridLayout.addWidget(self.comboBoxSelectStimId, 0, 0, 1, 2)
        self.groupboxMetaData = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupboxMetaData.setGeometry(QtCore.QRect(10, 190, 387, 205))
        self.groupboxMetaData.setObjectName("groupboxMetaData")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupboxMetaData)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.buttonStartExperiment = QtWidgets.QPushButton(self.groupboxMetaData)
        self.buttonStartExperiment.setCheckable(True)
        self.buttonStartExperiment.setObjectName("buttonStartExperiment")
        self.gridLayout_6.addWidget(self.buttonStartExperiment, 1, 2, 1, 2)
        self.buttonSetWorkingDirectory = QtWidgets.QPushButton(self.groupboxMetaData)
        self.buttonSetWorkingDirectory.setObjectName("buttonSetWorkingDirectory")
        self.gridLayout_6.addWidget(self.buttonSetWorkingDirectory, 1, 0, 1, 2)
        self.widgetMetaData = QtWidgets.QWidget(self.groupboxMetaData)
        self.widgetMetaData.setObjectName("widgetMetaData")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetMetaData)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.spinboxCrowdsize = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinboxCrowdsize.setProperty("value", 1)
        self.spinboxCrowdsize.setObjectName("spinboxCrowdsize")
        self.gridLayout_7.addWidget(self.spinboxCrowdsize, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 2, 0, 1, 1)
        self.spinBoxExperimentDurationMinutes = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinBoxExperimentDurationMinutes.setProperty("value", 5)
        self.spinBoxExperimentDurationMinutes.setObjectName("spinBoxExperimentDurationMinutes")
        self.gridLayout_7.addWidget(self.spinBoxExperimentDurationMinutes, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 2, 2, 1, 2)
        self.spinBoxExperimentDurationSeconds = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinBoxExperimentDurationSeconds.setObjectName("spinBoxExperimentDurationSeconds")
        self.gridLayout_7.addWidget(self.spinBoxExperimentDurationSeconds, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 2, 5, 1, 2)
        self.checkBoxExperimentAutonaming = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkBoxExperimentAutonaming.setChecked(True)
        self.checkBoxExperimentAutonaming.setObjectName("checkBoxExperimentAutonaming")
        self.gridLayout_7.addWidget(self.checkBoxExperimentAutonaming, 1, 6, 1, 1)
        self.labelMetaDataDrugName = QtWidgets.QLabel(self.widgetMetaData)
        self.labelMetaDataDrugName.setObjectName("labelMetaDataDrugName")
        self.gridLayout_7.addWidget(self.labelMetaDataDrugName, 5, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 3, 2, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.widgetMetaData)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_7.addWidget(self.spinBox, 3, 4, 1, 1)
        self.checkboxMetaDataDechorionation = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkboxMetaDataDechorionation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxMetaDataDechorionation.setObjectName("checkboxMetaDataDechorionation")
        self.gridLayout_7.addWidget(self.checkboxMetaDataDechorionation, 3, 5, 1, 2)
        self.checkboxMetaDataGenetics = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkboxMetaDataGenetics.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxMetaDataGenetics.setObjectName("checkboxMetaDataGenetics")
        self.gridLayout_7.addWidget(self.checkboxMetaDataGenetics, 4, 0, 1, 1)
        self.labelMetaDataGenetics = QtWidgets.QLabel(self.widgetMetaData)
        self.labelMetaDataGenetics.setObjectName("labelMetaDataGenetics")
        self.gridLayout_7.addWidget(self.labelMetaDataGenetics, 4, 1, 1, 2)
        self.lineeditMetaDataGenetics = QtWidgets.QLineEdit(self.widgetMetaData)
        self.lineeditMetaDataGenetics.setObjectName("lineeditMetaDataGenetics")
        self.gridLayout_7.addWidget(self.lineeditMetaDataGenetics, 4, 3, 1, 4)
        self.checkboxMetaDataDrugs = QtWidgets.QCheckBox(self.widgetMetaData)
        self.checkboxMetaDataDrugs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxMetaDataDrugs.setObjectName("checkboxMetaDataDrugs")
        self.gridLayout_7.addWidget(self.checkboxMetaDataDrugs, 5, 0, 1, 1)
        self.lineeditMetaDataDrugName = QtWidgets.QLineEdit(self.widgetMetaData)
        self.lineeditMetaDataDrugName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineeditMetaDataDrugName.setObjectName("lineeditMetaDataDrugName")
        self.gridLayout_7.addWidget(self.lineeditMetaDataDrugName, 5, 3, 1, 4)
        self.lineeditExperimentName = QtWidgets.QLineEdit(self.widgetMetaData)
        self.lineeditExperimentName.setEnabled(False)
        self.lineeditExperimentName.setObjectName("lineeditExperimentName")
        self.gridLayout_7.addWidget(self.lineeditExperimentName, 1, 0, 1, 6)
        self.label_11 = QtWidgets.QLabel(self.widgetMetaData)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 2)
        self.gridLayout_6.addWidget(self.widgetMetaData, 0, 0, 1, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabExperiment)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 0, 124, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.sliderVibrationStrength = QtWidgets.QSlider(self.groupBox_3)
        self.sliderVibrationStrength.setGeometry(QtCore.QRect(10, 109, 19, 72))
        self.sliderVibrationStrength.setMaximum(255)
        self.sliderVibrationStrength.setOrientation(QtCore.Qt.Vertical)
        self.sliderVibrationStrength.setObjectName("sliderVibrationStrength")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 23, 16, 16))
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox.setGeometry(QtCore.QRect(35, 109, 53, 20))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(35, 135, 53, 20))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(35, 161, 53, 20))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(94, 161, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(94, 135, 20, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(94, 109, 20, 16))
        self.label_18.setObjectName("label_18")
        self.lightStimuliGroup = QtWidgets.QGroupBox(self.tabExperiment)
        self.lightStimuliGroup.setEnabled(True)
        self.lightStimuliGroup.setGeometry(QtCore.QRect(10, 0, 311, 191))
        self.lightStimuliGroup.setObjectName("lightStimuliGroup")
        self.labelSeconds1 = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelSeconds1.setGeometry(QtCore.QRect(235, 110, 39, 16))
        self.labelSeconds1.setObjectName("labelSeconds1")
        self.spinboxStimStart = QtWidgets.QDoubleSpinBox(self.lightStimuliGroup)
        self.spinboxStimStart.setGeometry(QtCore.QRect(164, 110, 65, 20))
        self.spinboxStimStart.setMaximum(1000.0)
        self.spinboxStimStart.setObjectName("spinboxStimStart")
        self.lineeditStimName = QtWidgets.QLineEdit(self.lightStimuliGroup)
        self.lineeditStimName.setGeometry(QtCore.QRect(164, 70, 133, 20))
        self.lineeditStimName.setObjectName("lineeditStimName")
        self.labelSeconds2 = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelSeconds2.setGeometry(QtCore.QRect(235, 136, 39, 16))
        self.labelSeconds2.setObjectName("labelSeconds2")
        self.labelLightStimSettings = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelLightStimSettings.setGeometry(QtCore.QRect(85, 23, 171, 16))
        self.labelLightStimSettings.setObjectName("labelLightStimSettings")
        self.labelStimName = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelStimName.setGeometry(QtCore.QRect(85, 70, 54, 16))
        self.labelStimName.setObjectName("labelStimName")
        self.labelStimDuration = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelStimDuration.setGeometry(QtCore.QRect(85, 136, 68, 16))
        self.labelStimDuration.setObjectName("labelStimDuration")
        self.labelTestStim = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelTestStim.setGeometry(QtCore.QRect(85, 110, 63, 16))
        self.labelTestStim.setObjectName("labelTestStim")
        self.spinboxStimDuration = QtWidgets.QDoubleSpinBox(self.lightStimuliGroup)
        self.spinboxStimDuration.setGeometry(QtCore.QRect(164, 140, 65, 20))
        self.spinboxStimDuration.setMaximum(1000.0)
        self.spinboxStimDuration.setObjectName("spinboxStimDuration")
        self.buttonSaveStim = QtWidgets.QPushButton(self.lightStimuliGroup)
        self.buttonSaveStim.setGeometry(QtCore.QRect(194, 160, 101, 23))
        self.buttonSaveStim.setObjectName("buttonSaveStim")
        self.toggleWhiteColor = QtWidgets.QSlider(self.lightStimuliGroup)
        self.toggleWhiteColor.setGeometry(QtCore.QRect(140, 42, 60, 21))
        self.toggleWhiteColor.setMaximum(1)
        self.toggleWhiteColor.setOrientation(QtCore.Qt.Horizontal)
        self.toggleWhiteColor.setObjectName("toggleWhiteColor")
        self.labelLightStimTypeLED = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelLightStimTypeLED.setGeometry(QtCore.QRect(95, 44, 47, 13))
        self.labelLightStimTypeLED.setObjectName("labelLightStimTypeLED")
        self.labelLightStimTypeWhite = QtWidgets.QLabel(self.lightStimuliGroup)
        self.labelLightStimTypeWhite.setGeometry(QtCore.QRect(200, 42, 61, 16))
        self.labelLightStimTypeWhite.setObjectName("labelLightStimTypeWhite")
        self.widgetLEDSliders = QtWidgets.QWidget(self.lightStimuliGroup)
        self.widgetLEDSliders.setEnabled(True)
        self.widgetLEDSliders.setGeometry(QtCore.QRect(10, 10, 71, 171))
        self.widgetLEDSliders.setObjectName("widgetLEDSliders")
        self.labelRedSliderValue = QtWidgets.QLabel(self.widgetLEDSliders)
        self.labelRedSliderValue.setGeometry(QtCore.QRect(0, 10, 20, 16))
        self.labelRedSliderValue.setObjectName("labelRedSliderValue")
        self.sliderRed = QtWidgets.QSlider(self.widgetLEDSliders)
        self.sliderRed.setGeometry(QtCore.QRect(0, 29, 19, 141))
        self.sliderRed.setMaximum(255)
        self.sliderRed.setOrientation(QtCore.Qt.Vertical)
        self.sliderRed.setObjectName("sliderRed")
        self.labelBlueSliderValue = QtWidgets.QLabel(self.widgetLEDSliders)
        self.labelBlueSliderValue.setGeometry(QtCore.QRect(48, 10, 19, 16))
        self.labelBlueSliderValue.setObjectName("labelBlueSliderValue")
        self.labelGreenSliderValue = QtWidgets.QLabel(self.widgetLEDSliders)
        self.labelGreenSliderValue.setGeometry(QtCore.QRect(23, 10, 19, 16))
        self.labelGreenSliderValue.setObjectName("labelGreenSliderValue")
        self.sliderBlue = QtWidgets.QSlider(self.widgetLEDSliders)
        self.sliderBlue.setGeometry(QtCore.QRect(50, 29, 19, 141))
        self.sliderBlue.setMaximum(255)
        self.sliderBlue.setOrientation(QtCore.Qt.Vertical)
        self.sliderBlue.setObjectName("sliderBlue")
        self.sliderGreen = QtWidgets.QSlider(self.widgetLEDSliders)
        self.sliderGreen.setGeometry(QtCore.QRect(25, 29, 19, 141))
        self.sliderGreen.setMaximum(255)
        self.sliderGreen.setOrientation(QtCore.Qt.Vertical)
        self.sliderGreen.setObjectName("sliderGreen")
        self.tabWidget.addTab(self.tabExperiment, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.sliderBlue.sliderMoved['int'].connect(self.labelBlueSliderValue.setNum)
        self.sliderGreen.sliderMoved['int'].connect(self.labelGreenSliderValue.setNum)
        self.sliderRed.sliderMoved['int'].connect(self.labelRedSliderValue.setNum)
        self.sliderCameraBrightness.valueChanged['int'].connect(self.labelCameraBrighness.setNum)
        self.sliderIRLight.valueChanged['int'].connect(self.label_22.setNum)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_4.setTitle(_translate("Form", "Live Data From Serial Connection"))
        self.label_19.setText(_translate("Form", "Incoming Message:"))
        self.labelSerialLiveIncoming.setText(_translate("Form", "TextLabel"))
        self.label_20.setText(_translate("Form", "Temperature:"))
        self.labelSerialLiveTemperature.setText(_translate("Form", "TextLabel"))
        self.serialControlsGroup.setTitle(_translate("Form", "Serial Connection to Setup"))
        self.buttonSerialConnect.setText(_translate("Form", "Connect"))
        self.labelSerialConnected.setText(_translate("Form", "Status: Not Connected"))
        self.lineeditWriteToSerial.setToolTip(_translate("Form", "<html><head/><body><p>Write to the Controller:<br/>White light on: &quot;wS&quot;<br/>White light off: &quot;wC&quot;</p><p>For LEDs: &quot;n&quot;+ nine digits setting RGB values<br/>example: &quot;n000255000&quot; set green leds on.<br/>LEDs off: &quot;nC&quot;</p><p>set IR light: &quot;i&quot;+three digits<br/>example: &quot;i255&quot; sets IR to full power.</p></body></html>"))
        self.buttonSerialScan.setText(_translate("Form", "Scan"))
        self.buttonWriteToSerial.setText(_translate("Form", "Send"))
        self.checkBoxReadSerialLive.setText(_translate("Form", "Read Serial Live"))
        self.groupBoxCameraControls.setTitle(_translate("Form", "Camera Controls"))
        self.buttonCameraPreview.setText(_translate("Form", "Live Preview"))
        self.label_5.setText(_translate("Form", "Framerate"))
        self.label_6.setText(_translate("Form", "fps"))
        self.label_9.setText(_translate("Form", "Exposure"))
        self.label_7.setText(_translate("Form", "Brightness"))
        self.labelCameraBrighness.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Gamma"))
        self.labelCameraGamma.setText(_translate("Form", "0"))
        self.label_21.setText(_translate("Form", "IR Light"))
        self.label_22.setText(_translate("Form", "0"))
        self.buttonCameraResetProperties.setText(_translate("Form", "reset"))
        self.groupBoxVideoControls.setTitle(_translate("Form", "VideoControls"))
        self.labelVideoName.setText(_translate("Form", "Video Name"))
        self.checkboxAutoNaming.setText(_translate("Form", "Automatic"))
        self.label_2.setText(_translate("Form", "Duration"))
        self.label_3.setText(_translate("Form", "minutes"))
        self.label_4.setText(_translate("Form", "seconds"))
        self.buttonSetPath.setText(_translate("Form", "Set Path"))
        self.buttonRecordVideo.setText(_translate("Form", "Record"))
        self.groupBoxCameraConnection.setTitle(_translate("Form", "Connect To Camera"))
        self.labelCameraConnectionStatus.setText(_translate("Form", "Status: Not Connected"))
        self.buttonScanForCameras.setText(_translate("Form", "scan"))
        self.buttonCameraConnectDisconnect.setText(_translate("Form", "connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConnections), _translate("Form", "Camera and Serial Connection"))
        self.groupBox_2.setTitle(_translate("Form", "ExperimentView"))
        self.buttonDeleteSelectedStim.setText(_translate("Form", "Delete Stim"))
        self.buttonSaveStimulusProfile.setText(_translate("Form", "Save Stimulus Profile"))
        self.buttonDeleteAllStims.setText(_translate("Form", "Delete All Stims"))
        self.buttonLoadStimulusProfile.setText(_translate("Form", "Load Stimulus Profile"))
        self.groupboxMetaData.setTitle(_translate("Form", "MetaData"))
        self.buttonStartExperiment.setText(_translate("Form", "Start Experiment"))
        self.buttonSetWorkingDirectory.setText(_translate("Form", "Set Working Directory"))
        self.label_10.setText(_translate("Form", "Crowdsize"))
        self.label_15.setText(_translate("Form", "Duration"))
        self.label_14.setText(_translate("Form", "minutes"))
        self.label_16.setText(_translate("Form", "seconds"))
        self.checkBoxExperimentAutonaming.setText(_translate("Form", "Auto"))
        self.labelMetaDataDrugName.setText(_translate("Form", "Drug name:"))
        self.label_12.setToolTip(_translate("Form", "<html><head/><body><p>Hours Post Hatching</p></body></html>"))
        self.label_12.setText(_translate("Form", "HPH"))
        self.checkboxMetaDataDechorionation.setText(_translate("Form", "Dechorionated"))
        self.checkboxMetaDataGenetics.setText(_translate("Form", "Genetics"))
        self.labelMetaDataGenetics.setText(_translate("Form", "Genotype:"))
        self.lineeditMetaDataGenetics.setText(_translate("Form", "None"))
        self.checkboxMetaDataDrugs.setText(_translate("Form", "Drugs"))
        self.lineeditMetaDataDrugName.setText(_translate("Form", "None"))
        self.label_11.setText(_translate("Form", "Experiment Name:"))
        self.groupBox_3.setTitle(_translate("Form", "VibrationStimuli"))
        self.label.setText(_translate("Form", "0"))
        self.label_13.setText(_translate("Form", "Hz"))
        self.label_17.setText(_translate("Form", "sec."))
        self.label_18.setText(_translate("Form", "sec."))
        self.lightStimuliGroup.setTitle(_translate("Form", "LightStimuli"))
        self.labelSeconds1.setText(_translate("Form", "seconds"))
        self.lineeditStimName.setToolTip(_translate("Form", "Give your stimulus a wonderful name!"))
        self.lineeditStimName.setText(_translate("Form", "GeneralStimName"))
        self.lineeditStimName.setPlaceholderText(_translate("Form", "GeneralLightStim"))
        self.labelSeconds2.setText(_translate("Form", "seconds"))
        self.labelLightStimSettings.setText(_translate("Form", "Lightstimulus type:"))
        self.labelStimName.setText(_translate("Form", "Stim Name:"))
        self.labelStimDuration.setText(_translate("Form", "Stim Duration:"))
        self.labelTestStim.setText(_translate("Form", "Start stim at:"))
        self.buttonSaveStim.setText(_translate("Form", "Add to Stims"))
        self.labelLightStimTypeLED.setText(_translate("Form", "LED Stim"))
        self.labelLightStimTypeWhite.setText(_translate("Form", "White Light"))
        self.labelRedSliderValue.setText(_translate("Form", "0"))
        self.labelBlueSliderValue.setText(_translate("Form", "0"))
        self.labelGreenSliderValue.setText(_translate("Form", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExperiment), _translate("Form", "Experiment Settings"))

from pyqtgraph import PlotWidget
